//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.admin {
    
    
    public partial class kitapdzn {
        
        /// <summary>
        /// litBaslik control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBaslik;
        
        /// <summary>
        /// txtKitapAdi control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtKitapAdi;
        
        /// <summary>
        /// txtYazar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtYazar;
        
        /// <summary>
        /// txtIsbn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtIsbn;
        
        /// <summary>
        /// txtYil control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtYil;
        
        /// <summary>
        /// btnKaydet control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnKaydet;
        
        /// <summary>
        /// lblMesaj control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMesaj;
    }
}


