//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.admin {
    
    
    public partial class uyedzn {
        
        /// <summary>
        /// litBaslik control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBaslik;
        
        /// <summary>
        /// txtKulad control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtKulad;
        
        /// <summary>
        /// txtSifre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSifre;
        
        /// <summary>
        /// ddlYetki control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYetki;
        
        /// <summary>
        /// ddlDurum control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDurum;
        
        /// <summary>
        /// btnKaydet control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnKaydet;
        
        /// <summary>
        /// lblMesaj control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMesaj;
    }
}


